services:
  - type: web
    name: motosegura-api
    env: docker
    region: ohio
    dockerfilePath: ./Dockerfile
    plan: free
    autoDeploy: true

    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production

      - key: PORT
        value: 8080

      # Cadena de conexión a Neon / Postgres
      - key: DefaultConnection
        value: Host=ep-sparkling-pine-a45o89mh-pooler.us-east-1.aws.neon.tech;Port=5432;Database=neondb;Username=neondb_owner;Password=npg_E8XWFI9gzQZJ;SSL Mode=Require

      # Opcional: también compatible con otra convención
      - key: ConnectionStrings__DefaultConnection
        value: Host=ep-sparkling-pine-a45o89mh-pooler.us-east-1.aws.neon.tech;Port=5432;Database=neondb;Username=neondb_owner;Password=npg_E8XWFI9gzQZJ;SSL Mode=Require

      # JWT
      - key: Jwt__Key
        value: supersecretkey12345678901234567890
      - key: Jwt__Issuer
        value: MotoSeguraAPI
      - key: Jwt__Audience
        value: MotoSeguraFrontend
