sonar.projectKey=jaofdev_MotoSegura
sonar.organization=jaofdev
sonar.host.url=https://sonarcloud.io
sonar.cs.opencover.reportsPaths=MotoSeguraAPI.Tests/coverage.opencover.xml
sonar.exclusions=**/Migrations/**,**/*.Tests.cs