sonar.projectKey=jhologic12_MotoSeguraAPI
sonar.working.directory=C:\\jaofdev\\MotoSeguraBackend\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=C:\\jaofdev\\MotoSeguraBackend
sonar.pullrequest.cache.basepath=C:\\jaofdev\\MotoSeguraBackend
sonar.sources=\
"C:\\jaofdev\\MotoSeguraBackend\\.github\\workflows\\sonarcloud.yml",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI.Tests\\obj\\MotoSeguraAPI.Tests.csproj.nuget.dgspec.json",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI.Tests\\obj\\project.assets.json",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI.Tests\\bin\\Debug\\net8.0\\appsettings.Development.json",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI.Tests\\bin\\Debug\\net8.0\\appsettings.json",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI.Tests\\bin\\Debug\\net8.0\\MotoSeguraAPI.deps.json",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI.Tests\\bin\\Debug\\net8.0\\MotoSeguraAPI.runtimeconfig.json",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI.Tests\\bin\\Debug\\net8.0\\MotoSeguraAPI.Tests.deps.json",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI.Tests\\bin\\Debug\\net8.0\\MotoSeguraAPI.Tests.runtimeconfig.json",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI.Tests\\obj\\Debug\\net8.0\\MotoSeguraAPI.Tests.sourcelink.json",\
"C:\\jaofdev\\MotoSeguraBackend\\payload-example.json",\
"C:\\jaofdev\\MotoSeguraBackend\\run-analysis.ps1",\
"C:\\jaofdev\\MotoSeguraBackend\\sonar-project.properties"

B94CE892-8B49-4B9D-B3B2-48F7EF3E014F.sonar.projectKey=jhologic12_MotoSeguraAPI:B94CE892-8B49-4B9D-B3B2-48F7EF3E014F
B94CE892-8B49-4B9D-B3B2-48F7EF3E014F.sonar.projectName=MotoSeguraAPI
B94CE892-8B49-4B9D-B3B2-48F7EF3E014F.sonar.projectBaseDir=C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI
B94CE892-8B49-4B9D-B3B2-48F7EF3E014F.sonar.sourceEncoding=utf-8
B94CE892-8B49-4B9D-B3B2-48F7EF3E014F.sonar.tests=
B94CE892-8B49-4B9D-B3B2-48F7EF3E014F.sonar.sources=\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\Controllers\\AuthController.cs",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\Controllers\\TrayectoController.cs",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\Controllers\\UserController.cs",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\Data\\ApplicationDbContext.cs",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\DTOs\\AcelerometroDto.cs",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\DTOs\\ConectividadDto.cs",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\DTOs\\CoordenadasDto.cs",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\DTOs\\EventoDetectadoDto.cs",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\DTOs\\GiroscopioDto.cs",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\DTOs\\GpsDto.cs",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\DTOs\\StartBikeRequest.cs",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\DTOs\\TrayectoDto.cs",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\DTOs\\UserLoginDto.cs",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\DTOs\\UserProfileDto.cs",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\DTOs\\UserRegisterDto.cs",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\DTOs\\VerificacionCascoDto.cs",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\Mappings\\TrayectoProfile.cs",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\Migrations\\20251105225223_GuidSupport.cs",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\Migrations\\20251105225223_GuidSupport.Designer.cs",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\Migrations\\20251105230923_UpdateModelsWithGuidAndValidation.cs",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\Migrations\\20251105230923_UpdateModelsWithGuidAndValidation.Designer.cs",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\Migrations\\20251105233222_InitialCreate.cs",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\Migrations\\20251105233222_InitialCreate.Designer.cs",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\Migrations\\20251110193049_AddTrayectoModel.cs",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\Migrations\\20251110193049_AddTrayectoModel.Designer.cs",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\Migrations\\20251110194714_UpdateTrayectoModel.cs",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\Migrations\\20251110194714_UpdateTrayectoModel.Designer.cs",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\Migrations\\20251110212706_AddUniqueEmailToUser.cs",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\Migrations\\20251110212706_AddUniqueEmailToUser.Designer.cs",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\Migrations\\ApplicationDbContextModelSnapshot.cs",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\Models\\EventLog.cs",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\Models\\Evento.cs",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\Models\\SubModels\\Acelerometro.cs",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\Models\\SubModels\\Conectividad.cs",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\Models\\SubModels\\Coordenadas.cs",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\Models\\SubModels\\Giroscopio.cs",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\Models\\SubModels\\Gps.cs",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\Models\\SubModels\\VerificacionCasco.cs",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\Models\\Trayecto.cs",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\Models\\User.cs",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\Program.cs",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\Services\\AuthService.cs",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\Services\\Interfaces\\IAuthService.cs",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\Services\\Interfaces\\IUserService.cs",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\Services\\JwtService.cs",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\Services\\UserService.cs",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\Validators\\AcelerometroDtoValidator.cs",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\Validators\\ConectividadDtoValidator.cs",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\Validators\\CoordenadasDtoValidator.cs",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\Validators\\GiroscopioDtoValidator.cs",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\Validators\\GpsDtoValidator.cs",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\Validators\\TrayectoValidatorRequestValidator.cs",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\obj\\Debug\\net8.0\\MotoSeguraAPI.GlobalUsings.g.cs",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\obj\\Debug\\net8.0\\.NETCoreApp,Version=v8.0.AssemblyAttributes.cs",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\obj\\Debug\\net8.0\\MotoSeguraAPI.AssemblyInfo.cs",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\obj\\Debug\\net8.0\\MotoSeguraAPI.MvcApplicationPartsAssemblyInfo.cs",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\appsettings.Development.json",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\appsettings.json",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\motosegura.db",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\MotoSeguraAPI.http",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\Properties\\launchSettings.json",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\obj\\MotoSeguraAPI.csproj.nuget.dgspec.json",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\obj\\project.assets.json",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\bin\\Debug\\net8.0\\appsettings.Development.json",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\bin\\Debug\\net8.0\\appsettings.json",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\bin\\Debug\\net8.0\\MotoSeguraAPI.deps.json",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\bin\\Debug\\net8.0\\MotoSeguraAPI.runtimeconfig.json",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\obj\\Debug\\net8.0\\MotoSeguraAPI.sourcelink.json",\
"C:\\jaofdev\\MotoSeguraBackend\\MotoSeguraAPI\\obj\\Debug\\net8.0\\staticwebassets.build.json"

B94CE892-8B49-4B9D-B3B2-48F7EF3E014F.sonar.cs.analyzer.projectOutPaths=\
"C:\\jaofdev\\MotoSeguraBackend\\.sonarqube\\out\\0"
B94CE892-8B49-4B9D-B3B2-48F7EF3E014F.sonar.cs.roslyn.reportFilePaths=\
"C:\\jaofdev\\MotoSeguraBackend\\.sonarqube\\out\\0\\Issues.json"
B94CE892-8B49-4B9D-B3B2-48F7EF3E014F.sonar.cs.scanner.telemetry=\
"C:\\jaofdev\\MotoSeguraBackend\\.sonarqube\\out\\0\\Telemetry.json"

B94CE892-8B49-4B9D-B3B2-48F7EF3E014F.sonar.working.directory=C:\\jaofdev\\MotoSeguraBackend\\.sonarqube\\out\\.sonar\\mod0
sonar.host.url=https://sonarcloud.io
sonar.organization=jaofdev
sonar.visualstudio.enable=false

sonar.modules=B94CE892-8B49-4B9D-B3B2-48F7EF3E014F

